In [1]:
import numpy as np

In [3]:
x=np.zeros((4,4))

In [4]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.empty((6,6))

array([[9.77824555e+199, 6.01334653e-154, 1.16034627e+200,
        1.39807419e-152, 7.62863758e+228, 1.62691064e+219],
       [4.26209402e+180, 1.13483828e-153, 2.43722657e-152,
        3.44747791e-085, 1.17518756e+180, 5.98189649e-154],
       [4.47593816e-091, 3.62459345e+228, 4.24438351e+175,
        1.03966460e-028, 4.83245961e+276, 6.01347002e-154],
       [1.38496762e+219, 1.21698002e-152, 2.66065731e-260,
        7.70858946e+218, 6.01334668e-154, 4.47593816e-091],
       [7.01413727e-009, 3.74168445e+233, 2.59345444e+161,
        2.58400946e+161, 1.00557086e+242, 2.96519945e-062],
       [2.04740462e+161, 1.05135755e-153, 2.44011708e-154,
        6.03394389e-154, 6.01347002e-154, 6.01347002e-154]])

In [7]:
l=[1,2,3,4]

In [8]:
np.array(l)

array([1, 2, 3, 4])

In [10]:
x=np.arange(1,100,10)

In [11]:
x.shape

(10,)

In [13]:
x=np.zeros((10,10))

In [14]:
x.shape

(10, 10)

In [15]:
y=x.reshape((2,2,5,5))

In [16]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [17]:
y.dtype

dtype('float64')

In [18]:
y.ndim

4

In [19]:
a=np.random.randn((10))

In [20]:
a

array([ 1.37027608, -1.3986627 ,  0.75193539, -0.98452946,  1.13972101,
        1.6950786 , -0.27223169,  1.50473773, -0.13128268,  0.48085336])

In [21]:
b=np.random.randn((10))

In [22]:
b

array([ 1.73454282, -0.3684827 , -0.40758987, -0.58396846,  0.61346371,
        0.4893153 ,  1.81575283,  1.29394202, -0.6063662 ,  0.67373083])

In [23]:
a+b

array([ 3.10481889, -1.7671454 ,  0.34434553, -1.56849791,  1.75318473,
        2.1843939 ,  1.54352113,  2.79867975, -0.73764887,  1.15458419])

In [24]:
a-b

array([-0.36426674, -1.03018001,  1.15952526, -0.400561  ,  0.5262573 ,
        1.2057633 , -2.08798452,  0.21079571,  0.47508352, -0.19287747])

In [25]:
2*a

array([ 2.74055215, -2.79732541,  1.50387079, -1.96905891,  2.27944203,
        3.3901572 , -0.54446339,  3.00947546, -0.26256535,  0.96170672])

In [26]:
1/a

array([ 0.72977995, -0.71496866,  1.32990149, -1.01571364,  0.87740771,
        0.58994315, -3.67334157,  0.66456764, -7.6171512 ,  2.07963609])

In [27]:
a>0

array([ True, False,  True, False,  True,  True, False,  True, False,
        True])

In [28]:
a[a>0]

array([1.37027608, 0.75193539, 1.13972101, 1.6950786 , 1.50473773,
       0.48085336])

In [30]:
x=np.array([1,7,8,9,5])

In [31]:
x[4]

5

In [32]:
x[x>5]

array([7, 8, 9])

In [35]:
x[[2,1]]

array([8, 7])

In [38]:
x=np.random.randn(10,10)

In [39]:
x

array([[ 2.00278075, -0.69206718, -0.01616107,  0.84195858,  1.03028679,
        -0.72829677, -0.06740609,  1.21261499,  0.7509485 , -1.78661761],
       [-1.26385008, -0.90846716, -0.55355887,  2.83588554, -0.81904221,
        -0.73063763, -0.47360535,  0.01877984,  0.18490913,  1.15872493],
       [-1.42720871,  0.7579914 ,  2.01061171, -0.15690981, -0.6649809 ,
        -0.25984356, -0.01166516,  0.10496317, -0.10182482, -0.65601397],
       [-0.79204255, -1.92811147, -0.61915835,  0.29298447,  1.35389085,
         0.67111105,  3.72108453,  1.23065323, -0.21396008,  0.61789445],
       [ 0.11589994, -0.74458607, -0.06569461, -0.05388524,  0.27839129,
        -1.38749574, -0.70329333,  0.70854527, -0.39202981, -0.43465921],
       [ 1.0083438 , -1.56604635, -0.83542015, -1.30828702,  0.01971677,
         0.04893317, -0.40451857,  0.14056293, -0.52948931,  0.16704301],
       [-0.3423087 , -0.42042228,  0.36400619,  1.04607304,  1.0104196 ,
         0.25592674, -1.08421893, -0.22672276

In [40]:
x[0]

array([ 2.00278075, -0.69206718, -0.01616107,  0.84195858,  1.03028679,
       -0.72829677, -0.06740609,  1.21261499,  0.7509485 , -1.78661761])

In [41]:
x[0][4]

1.0302867876645263

In [42]:
x[1:10:2,::]

array([[-1.26385008, -0.90846716, -0.55355887,  2.83588554, -0.81904221,
        -0.73063763, -0.47360535,  0.01877984,  0.18490913,  1.15872493],
       [-0.79204255, -1.92811147, -0.61915835,  0.29298447,  1.35389085,
         0.67111105,  3.72108453,  1.23065323, -0.21396008,  0.61789445],
       [ 1.0083438 , -1.56604635, -0.83542015, -1.30828702,  0.01971677,
         0.04893317, -0.40451857,  0.14056293, -0.52948931,  0.16704301],
       [ 0.3274605 , -1.05835747,  1.12485558,  0.3884826 ,  0.80929772,
         1.9670673 ,  0.7524731 ,  1.58512856,  0.97327747, -1.43780068],
       [-0.50938153, -0.07289105,  1.5210143 , -0.37268213, -0.18861803,
        -0.60815378,  0.04497583, -0.12690167, -0.25925936,  0.18572935]])

In [43]:
x[::,0:4]

array([[ 2.00278075, -0.69206718, -0.01616107,  0.84195858],
       [-1.26385008, -0.90846716, -0.55355887,  2.83588554],
       [-1.42720871,  0.7579914 ,  2.01061171, -0.15690981],
       [-0.79204255, -1.92811147, -0.61915835,  0.29298447],
       [ 0.11589994, -0.74458607, -0.06569461, -0.05388524],
       [ 1.0083438 , -1.56604635, -0.83542015, -1.30828702],
       [-0.3423087 , -0.42042228,  0.36400619,  1.04607304],
       [ 0.3274605 , -1.05835747,  1.12485558,  0.3884826 ],
       [ 1.20911877,  1.44381422, -0.52377741,  0.86430801],
       [-0.50938153, -0.07289105,  1.5210143 , -0.37268213]])

In [44]:
x=np.ones((5,5))

In [45]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
x[1:-1,1:-1]=0

In [49]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
x=np.array([10,9,8,56,11])

In [51]:
x

array([10,  9,  8, 56, 11])

In [52]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 7.48331477, 3.31662479])

In [53]:
np.power(x,2)

array([ 100,   81,   64, 3136,  121], dtype=int32)

In [54]:
y=[7,1,2,3,-1]

In [55]:
np.maximum(x,y)

array([10,  9,  8, 56, 11])